USE chapter_four;

CREATE TABLE chapter_four
(
	polski VARCHAR(300),
    angielski VARCHAR(300),
    poziom INT,
    obraz VARCHAR(400),
	przyklada VARCHAR(400),
    przykladb VARCHAR(400),
    przykladc VARCHAR(400),
    przykladd VARCHAR(400)
);

INSERT INTO chapter_four(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('grzywka', 'bangs', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\grzywka.png', 'Mam nową grzywkę.', 'I have new bangs.', 'Podoba mi się Twoja grzywka.', 'I like your bangs.'),
	('fryzjer', 'barber', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\fryc.png', 'Idę do fryzjera.', 'I am going to the barber.', 'Fryzjer obciął mi włosy.', 'The barber cut my hair.'),
	('makijaż', 'makeup', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\make.png', 'Używam codziennie makijażu.', 'I use makeup every day.', 'Potrzebuję nowego zestawu do makijażu.', 'I need a new makeup kit.'),
	('włosy', 'hairs', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\wlosy.png', 'Moje włosy są długie.', 'My hairs are long.', 'Mam kręcone włosy.', 'I have curly hairs.'),
	('kosmetyczka', 'beautician', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kosme.png', 'Kosmetyczka poleciła mi ten krem.', 'The beautician recommended this cream to me.', 'Mam wizytę u kosmetyczki.', 'I have an appointment with the beautician.'),
	('zapach', 'fragrance', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\zapach.png', 'Ten zapach jest piękny.', 'This fragrance is beautiful.', 'Lubię zapach świeżych kwiatów.', 'I like the fragrance of fresh flowers.'),
	('pielęgnacja skóry', 'skincare', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\skora.png', 'Pielęgnacja skóry jest ważna.', 'Skincare is important.', 'Mam rutynę pielęgnacji skóry.', 'I have a skincare routine.'),
	('tłusta', 'oily', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\tlusty.png', 'Mam tłustą skórę.', 'I have oily skin.', 'Ten produkt jest dobry do skóry tłustej.', 'This product is good for oily skin.'),
	('sucha', 'dry', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\dry.png', 'Moja skóra jest sucha.', 'My skin is dry.', 'Potrzebuję kremu do suchej skóry.', 'I need a cream for dry skin.'),
	('płyn do mycia twarzy', 'face wash', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\plyn.png', 'Używam płynu do mycia twarzy.', 'I use face wash.', 'Ten płyn do mycia twarzy jest delikatny.', 'This face wash is gentle.'),
	('krem pod oczy', 'eye cream', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\krem.png', 'Nakładam krem pod oczy.', 'I apply eye cream.', 'Ten krem pod oczy jest nawilżający.', 'This eye cream is moisturizing.'),
	('kosmetyki', 'cosmetics', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kosmetyki.png', 'Kupuję kosmetyki online.', 'I buy cosmetics online.', 'Lubię testować nowe kosmetyki.', 'I like to test new cosmetics.'),
	('metamorfoza', 'makeover', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\zmiana.png', 'Zrobiłam metamorfozę swojego wyglądu.', 'I did a makeover of my look.', 'Programy o metamorfozach są interesujące.', 'Makeover shows are interesting.'),
	('konkurs piękności', 'beauty pageant', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\piekna.png', 'Wzięłam udział w konkursie piękności.', 'I participated in a beauty pageant.', 'Konkursy piękności są popularne.', 'Beauty pageants are popular.'),
	('puszysty', 'fluffy', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\puszysty.png', 'Moje włosy są puszyste.', 'My hair is fluffy.', 'Używam produktów, które nadają włosom puszystość.', 'I use products that make hair fluffy.'),
	('solarium', 'solarium', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\solarium.png', 'Idę do solarium.', 'I am going to the solarium.', 'Solarium jest zamknięte dzisiaj.', 'The solarium is closed today.'),
	('ścięcie włosów', 'haircut', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\sciac.png', 'Potrzebuję ścięcia włosów.', 'I need a haircut.', 'Umówiłem się na ścięcie włosów.', 'I scheduled a haircut.'),
	('spinka', 'clip', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\klip.png', 'Używam spinki do włosów.', 'I use a hair clip.', 'Moja spinka jest zepsuta.', 'My hair clip is broken.'),
	('kręcić się', 'curl', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\krec.png', 'Moje włosy kręcą się naturalnie.', 'My hair curls naturally.', 'Lubię kręcić włosy na lokówce.', 'I like to curl my hair with a curler.'),
	('farbować', 'dye', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\farbowac.png', 'Farbowanie włosów jest popularne.', 'Dyeing hair is popular.', 'Zamierzam farbować włosy na blond.', 'I plan to dye my hair blonde.'),
	('produkt kosmetyczny', 'beauty product', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kosmetyki.png', 'Kupiłam nowy produkt kosmetyczny.', 'I bought a new beauty product.', 'Ten produkt kosmetyczny jest świetny.', 'This beauty product is great.'),
	('uczesanie', 'hairstyling', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\czesac.png', 'Lubię uczesać włosy rano.', 'I like to do my hairstyling in the morning.', 'Uczesanie włosów zajmuje mi 10 minut.', 'Hairstyling takes me 10 minutes.'),
	('brzytwa/ golarka', 'razor', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\golarka.png', 'Używam brzytwy do golenia.', 'I use a razor for shaving.', 'Brzytwa jest ostra.', 'The razor is sharp.'),
	('pielęgnacja paznokci', 'nail care', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\paznokiec.png', 'Pielęgnacja paznokci jest ważna.', 'Nail care is important.', 'Mam zestaw do pielęgnacji paznokci.', 'I have a nail care set.'),
	('lakier', 'polish', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\lakier.png', 'Używam lakieru do paznokci.', 'I use nail polish.', 'Mój lakier jest czerwony.', 'My nail polish is red.'),
	('krem nawilżający', 'moisturising cream', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\krem2.png', 'Krem nawilżający jest niezbędny.', 'Moisturising cream is essential.', 'Używam kremu nawilżającego codziennie.', 'I use moisturizing cream daily.'),
	('odżywka', 'conditioner', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\odzywka.png', 'Odżywka do włosów jest ważna.', 'Conditioner is important for hair.', 'Ta odżywka jest dobra do suchych włosów.', 'This conditioner is good for dry hair.'),
	('suszyć suszarką', 'blow dry', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\dry2.png', 'Suszę włosy suszarką.', 'I blow dry my hair.', 'Suszarka jest zepsuta.', 'The blow dryer is broken.'),
	('nakładać', 'apply', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\naloz.png', 'Nakładam krem na twarz.', 'I apply cream to my face.', 'Nakładanie makijażu zajmuje mi 15 minut.', 'Applying makeup takes me 15 minutes.'),
	('wodoodporny', 'waterproof', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\wodo.png', 'Ten tusz jest wodoodporny.', 'This mascara is waterproof.', 'Potrzebuję wodoodpornego makijażu.', 'I need waterproof makeup.'),
	('płatki kosmetyczne', 'cotton pads', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\platki.png', 'Używam płatków kosmetycznych.', 'I use cotton pads.', 'Płatki kosmetyczne są bardzo wygodne.', 'Cotton pads are very convenient.'),
	('pielęgnacja', 'care', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\piel.png', 'Pielęgnacja jest ważna.', 'Care is important.', 'Dobra pielęgnacja skóry zapewnia zdrowy wygląd.', 'Good skincare ensures a healthy look.'),
	('balsam do ciała', 'body lotion', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\balsam.png', 'Używam balsamu do ciała po kąpieli.', 'I use body lotion after a bath.', 'Balsam do ciała nawilża skórę.', 'Body lotion moisturizes the skin.'),
	('salon urody', 'beauty salon', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\salon.png', 'Idę do salonu urody.', 'I am going to the beauty salon.', 'Salon urody oferuje wiele zabiegów.', 'The beauty salon offers many treatments.'),
	('pilnik do paznokci', 'nail file', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\pilnik.png', 'Używam pilnika do paznokci.', 'I use a nail file.', 'Pilnik do paznokci jest wygodny.', 'The nail file is convenient.'),
	('obcinacz', 'nail clipper', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\obcinacz.png', 'Mam nowy obcinacz do paznokci.', 'I have a new nail clipper.', 'Obcinacz jest bardzo ostry.', 'The nail clipper is very sharp.'),
	('pomadka', 'lipstick', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\pomadka.png', 'Lubię nosić pomadkę.', 'I like to wear lipstick.', 'Moja pomadka jest czerwona.', 'My lipstick is red.');
    
    INSERT INTO chapter_four(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
    VALUES
		('pasować', 'fit', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\pasowac.png', 'Te spodnie pasują idealnie.', 'These pants fit perfectly.', 'Czy ta koszula pasuje do mojej spódnicy?', 'Does this shirt fit my skirt?'),
		('Jak wyglądam', 'How Do I look?', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\jak.png', 'Jak wyglądam w tej sukience?', 'How do I look in this dress?', 'Jak wyglądam w tym garniturze?', 'How do I look in this suit?'),
		('biżuteria', 'jewellery', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\bizuteria.png', 'Lubię nosić biżuterię.', 'I like to wear jewellery.', 'Ta biżuteria jest piękna.', 'This jewellery is beautiful.'),
		('odpowiednio ubrany', 'dressed properly', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\ubrac.png', 'Jestem odpowiednio ubrany na tę okazję.', 'I am dressed properly for this occasion.', 'Czy jesteś odpowiednio ubrany na spotkanie?', 'Are you dressed properly for the meeting?'),
		('strój', 'outfit', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\stroj.png', 'Twój strój jest elegancki.', 'Your outfit is elegant.', 'Zmieniam swój strój na wieczór.', 'I am changing my outfit for the evening.'),
		('strój dzienny', 'daytime wear', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\stroj2.png', 'To jest mój ulubiony strój dzienny.', 'This is my favorite daytime wear.', 'Potrzebuję nowego stroju dziennego.', 'I need new daytime wear.'),
		('niemodny', 'not fashionable', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\przedstawienie.png', 'Ten sweter jest niemodny.', 'This sweater is not fashionable.', 'Twoje buty są niemodne.', 'Your shoes are not fashionable.'),
		('niechlujny', 'slovenly', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\przedstawienie.png', 'Wyglądasz niechlujnie.', 'You look slovenly.', 'Nie chcę być niechlujny na tej imprezie.', 'I don''t want to be slovenly at this party.'),
		('koszula', 'shirt', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\koszula.png', 'Kupuję nową koszulę.', 'I am buying a new shirt.', 'Ta koszula jest za mała.', 'This shirt is too small.'),
		('spódnica', 'skirt', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\spodnica.png', 'Lubię nosić spódnice.', 'I like to wear skirts.', 'Ta spódnica jest za krótka.', 'This skirt is too short.'),
		('apaszka/ szal/ chusta', 'scarf', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\szalik.png', 'Noszę apaszkę na szyi.', 'I wear a scarf around my neck.', 'Potrzebuję nowej chusty.', 'I need a new scarf.'),
		('właściwy rozmiar', 'right size', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\rozmiar.png', 'To jest właściwy rozmiar.', 'This is the right size.', 'Sprawdź, czy to jest właściwy rozmiar.', 'Check if this is the right size.'),
		('sweter', 'sweater', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\sweter.png', 'Mam ciepły sweter.', 'I have a warm sweater.', 'Potrzebuję nowego swetra na zimę.', 'I need a new sweater for winter.'),
		('spodnie', 'pants', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\spodnie.png', 'Te spodnie są wygodne.', 'These pants are comfortable.', 'Lubię nosić luźne spodnie.', 'I like to wear loose pants.'),
		('kurtka/ marynarka', 'jacket', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kurtka.png', 'To jest moja ulubiona kurtka.', 'This is my favorite jacket.', 'Ta marynarka jest elegancka.', 'This jacket is elegant.'),
		('czapka z daszkiem', 'cap', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\czapa.png', 'Noszę czapkę z daszkiem.', 'I wear a cap.', 'Ta czapka z daszkiem jest nowa.', 'This cap is new.'),
		('garnitur', 'suit', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\garnitur.png', 'Kupiłem nowy garnitur.', 'I bought a new suit.', 'Ten garnitur jest na miarę.', 'This suit is tailored.'),
		('sklep z odzieżą używaną', 'second hand store', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\sklep.png', 'Kupuję ubrania w sklepie z odzieżą używaną.', 'I buy clothes in a second hand store.', 'Ten sklep z odzieżą używaną ma świetne oferty.', 'This second hand store has great deals.'),
		('kurtka skórzana', 'leather jacket', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\skora2.png', 'Noszę kurtkę skórzaną.', 'I wear a leather jacket.', 'Ta kurtka skórzana jest stylowa.', 'This leather jacket is stylish.'),
		('rękaw', 'sleeve', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\rekaw.png', 'Mój rękaw jest za długi.', 'My sleeve is too long.', 'Muszę skrócić rękawy tej koszuli.', 'I need to shorten the sleeves of this shirt.'),
		('płaszcz zimowy', 'winter coat', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\plaszcz.png', 'Mam nowy płaszcz zimowy.', 'I have a new winter coat.', 'Ten płaszcz zimowy jest bardzo ciepły.', 'This winter coat is very warm.'),
		('suknia balowa', 'ball gown', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\suknia.png', 'Noszę suknię balową na przyjęcie.', 'I wear a ball gown to the party.', 'Ta suknia balowa jest przepiękna.', 'This ball gown is gorgeous.'),
		('rajstopy', 'tights', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\rajstopy.png', 'Lubię nosić rajstopy.', 'I like to wear tights.', 'Te rajstopy są wygodne.', 'These tights are comfortable.'),
		('dodatki', 'accessories', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\doda.png', 'Mam nowe dodatki do mojego stroju.', 'I have new accessories for my outfit.', 'Te dodatki są bardzo modne.', 'These accessories are very trendy.'),
		('modny', 'trendy', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\modny.png', 'Twoje ubrania są bardzo modne.', 'Your clothes are very trendy.', 'Lubię modny styl.', 'I like trendy fashion.'),
		('przymierzyć', 'try on', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\try.png', 'Chcę przymierzyć tę sukienkę.', 'I want to try on this dress.', 'Przymierzę ten płaszcz.', 'I will try on this coat.'),
		('wełna', 'wool', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\welna.png', 'Ten sweter jest z wełny.', 'This sweater is made of wool.', 'Wełniane ubrania są ciepłe.', 'Wool clothes are warm.'),
		('bawełna', 'cotton', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\bawelna.png', 'Ta koszula jest z bawełny.', 'This shirt is made of cotton.', 'Bawełna jest miękka i wygodna.', 'Cotton is soft and comfortable.'),
		('jedwab', 'silk', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\jedwab.png', 'Ta bluzka jest z jedwabiu.', 'This blouse is made of silk.', 'Jedwab jest luksusowy.', 'Silk is luxurious.'),
        ('len', 'linen', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\lin.png', 'Noszę lniane spodnie latem.', 'I wear linen pants in summer.', 'Len jest przewiewny.', 'Linen is breathable.'),
		('w kratę', 'checked', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\krata.png', 'Mam koszulę w kratę.', 'I have a checked shirt.', 'Lubię ubrania w kratę.', 'I like checked clothes.'),
		('w pasy', 'striped', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\pas.png', 'Moja koszula jest w pasy.', 'My shirt is striped.', 'Te spodnie są w pasy.', 'These pants are striped.'),
		('gładki', 'plain', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\gladki.png', 'Noszę gładkie koszulki.', 'I wear plain T-shirts.', 'Gładkie ubrania są uniwersalne.', 'Plain clothes are versatile.'),
		('bluza z kapturem', 'hoodie', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kaptur.png', 'Lubię nosić bluzę z kapturem.', 'I like to wear a hoodie.', 'Moja bluza z kapturem jest ciepła.', 'My hoodie is warm.'),
		('sweter rozpinany', 'cardigan', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kard.png', 'Noszę rozpinany sweter.', 'I wear a cardigan.', 'Ten rozpinany sweter jest wygodny.', 'This cardigan is comfortable.'),
		('bluza', 'jersey', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\jer.png', 'Lubię nosić bluzę.', 'I like to wear a jersey.', 'Moja bluza jest miękka.', 'My jersey is soft.'),
		('dres', 'tracksuit', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\dres.png', 'Lubię chodzić w dresie.', 'I like to wear a tracksuit.', 'Mój dres jest wygodny.', 'My tracksuit is comfortable.'),
		('krótkie spodenki', 'shorts', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\spodenki.png', 'Noszę krótkie spodenki latem.', 'I wear shorts in summer.', 'Te krótkie spodenki są stylowe.', 'These shorts are stylish.'),
		('majtki', 'panties', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\majtki.png', 'Potrzebuję nowych majtek.', 'I need new panties.', 'Te majtki są wygodne.', 'These panties are comfortable.'),
		('bokserki', 'boxer shorts', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\box.png', 'Noszę bokserki.', 'I wear boxer shorts.', 'Te bokserki są z bawełny.', 'These boxer shorts are made of cotton.'),
		('slipy', 'briefs', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\slipy.png', 'Potrzebuję nowych slipów.', 'I need new briefs.', 'Te slipy są wygodne.', 'These briefs are comfortable.'),
		('szlafrok', 'bathrobe', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\szlaf.png', 'Lubię nosić szlafrok po kąpieli.', 'I like to wear a bathrobe after a bath.', 'Mój szlafrok jest miękki.', 'My bathrobe is soft.'),
		('piżama', 'pyjamas', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\pizama.png', 'Mam wygodną piżamę.', 'I have comfortable pyjamas.', 'Noszę piżamę do spania.', 'I wear pyjamas to sleep.'),
		('wiatrówka', 'anorak', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\wiatr.png', 'Mam nową wiatrówkę.', 'I have a new anorak.', 'Moja wiatrówka jest wodoodporna.', 'My anorak is waterproof.'),
		('muszka', 'bow tie', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\mucha.png', 'Noszę muszkę na specjalne okazje.', 'I wear a bow tie on special occasions.', 'Ta muszka jest elegancka.', 'This bow tie is elegant.'),
		('krawat', 'tie', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\tie.png', 'Kupuję nowy krawat.', 'I am buying a new tie.', 'Twój krawat jest modny.', 'Your tie is trendy.'),
		('buty na obcasie', 'high heels', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\obcas.png', 'Lubię nosić buty na obcasie.', 'I like to wear high heels.', 'Te buty na obcasie są wygodne.', 'These high heels are comfortable.'),
		('szpilki', 'stilettos', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\szpila.png', 'Noszę szpilki na przyjęcia.', 'I wear stilettos to parties.', 'Te szpilki są eleganckie.', 'These stilettos are elegant.'),
		('trampki', 'canvas shoes', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\trampki.png', 'Lubię nosić trampki.', 'I like to wear canvas shoes.', 'Moje trampki są wygodne.', 'My canvas shoes are comfortable.'),
		('klapki', 'flip flops', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\klapki.png', 'Noszę klapki na plażę.', 'I wear flip flops to the beach.', 'Te klapki są wygodne.', 'These flip flops are comfortable.'),
		('kalosze', 'wellingtons', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons4\\kalosz.png', 'Mam kalosze na deszczowe dni.', 'I have wellingtons for rainy days.', 'Te kalosze są wodoodporne.', 'These wellingtons are waterproof.');
        
SELECT *FROM chapter_four;

DROP TABLE chapter_four;
    