USE chapter_three;

CREATE TABLE chapter_three
(
	polski VARCHAR(300),
    angielski VARCHAR(300),
    poziom INT,
    obraz VARCHAR(400),
	przyklada VARCHAR(400),
    przykladb VARCHAR(400),
    przykladc VARCHAR(400),
    przykladd VARCHAR(400)
);

INSERT INTO chapter_three(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('katar', 'runny nose', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\katar.png', 'Mam katar.', 'I have a runny nose.', 'Czy masz coś na katar?', 'Do you have something for a runny nose?'),
    ('kichać', 'sneeze', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kichac.png', 'Nie mogę przestać kichać.', 'I can''t stop sneezing.', 'Czy ktoś tu kichał?', 'Did someone sneeze here?'),
    ('zatkane zatoki', 'stuffy head', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zatoki.png', 'Mam zatkane zatoki.', 'I have a stuffy head.', 'Zatkane zatoki sprawiają, że źle się czuję.', 'A stuffy head makes me feel bad.'),
    ('kaszleć', 'cough', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kaszlec.png', 'Ciągle kaszlę.', 'I keep coughing.', 'Kaszel jest naprawdę dokuczliwy.', 'The cough is really bothersome.'),
    ('alergia', 'allergy', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\alergia.png', 'Mam alergię na pyłki.', 'I have an allergy to pollen.', 'Czy to alergia?', 'Is this an allergy?'),
    ('przeziębienie', 'cold', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\chory.png', 'Złapałem przeziębienie.', 'I caught a cold.', 'Przeziębienie trwa już tydzień.', 'The cold has lasted a week.'),
    ('boleć', 'hurt', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\bol.png', 'Boli mnie ręka.', 'My arm hurts.', 'Czy coś cię boli?', 'Does anything hurt?'),
    ('tabletka', 'pill', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tabletka.png', 'Weź tę tabletkę.', 'Take this pill.', 'Czy mogę dostać tabletki przeciwbólowe?', 'Can I get painkillers?'),
    ('objaw/ symptom', 'symptom', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\objaw.png', 'Jakie masz objawy?', 'What symptoms do you have?', 'Gorączka to jeden z objawów.', 'Fever is one of the symptoms.'),
    ('gorączka', 'fever', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\goraczka.png', 'Mam wysoką gorączkę.', 'I have a high fever.', 'Gorączka spadła.', 'The fever has gone down.'),
    ('zawroty głowy', 'dizziness', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zawroty.png', 'Mam zawroty głowy.', 'I have dizziness.', 'Czy zawroty głowy są częste?', 'Is dizziness frequent?'),
    ('senność', 'drowsiness', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\senny.png', 'Czuję senność.', 'I feel drowsy.', 'Senność to efekt uboczny.', 'Drowsiness is a side effect.'),
    ('nudności', 'nausea', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\nudnosci.png', 'Mam nudności.', 'I have nausea.', 'Nudności są nie do zniesienia.', 'The nausea is unbearable.'),
    ('wymioty', 'vomiting', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wymioty.png', 'Zacząłem wymiotować.', 'I started vomiting.', 'Czy wymioty ustąpiły?', 'Has the vomiting stopped?'),
    ('szwy', 'stitches', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\szwy.png', 'Mam szwy na ręce.', 'I have stitches on my arm.', 'Kiedy zdejmą mi szwy?', 'When will they remove my stitches?'),
    ('stan', 'condition', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\stan.png', 'Jaki jest jego stan?', 'What is his condition?', 'Mój stan się poprawia.', 'My condition is improving.'),
    ('badanie', 'examination', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\badac.png', 'Potrzebuję badania lekarskiego.', 'I need a medical examination.', 'Badanie trwało godzinę.', 'The examination took an hour.'),
    ('biegunka', 'diarrhoea', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\biegunka.png', 'Mam biegunkę.', 'I have diarrhoea.', 'Biegunka mnie wykończy.', 'The diarrhoea is wearing me out.'),
    ('złamanie', 'broken', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zlamanie.png', 'Złamałem rękę.', 'I broke my arm.', 'Czy to złamanie jest poważne?', 'Is the broken bone serious?'),
    ('blizna', 'scar', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\blizna.png', 'Mam bliznę po operacji.', 'I have a scar from the surgery.', 'Blizna jest jeszcze świeża.', 'The scar is still fresh.'),
    ('krztusić się', 'choke', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kaszlec.png', 'Zacząłem się krztusić.', 'I started to choke.', 'Czy ktoś może się krztusić?', 'Can someone choke?'),
    ('wysypka', 'rash', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wysypka.png', 'Mam wysypkę na skórze.', 'I have a rash on my skin.', 'Czy wysypka swędzi?', 'Does the rash itch?'),
    ('zmęczenie', 'fatigue', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\senny.png', 'Czuję zmęczenie.', 'I feel fatigue.', 'Zmęczenie jest ciągłe.', 'The fatigue is constant.'),
    ('recepta', 'prescription', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\recepta.png', 'Potrzebuję recepty.', 'I need a prescription.', 'Czy masz receptę na te leki?', 'Do you have a prescription for these drugs?'),
    ('apteka', 'pharmacy', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\apteka.png', 'Muszę iść do apteki.', 'I need to go to the pharmacy.', 'Gdzie jest najbliższa apteka?', 'Where is the nearest pharmacy?'),
    ('połknąć', 'swallow', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\polknac.png', 'Nie mogę połknąć tej tabletki.', 'I can''t swallow this pill.', 'Połknij to szybko.', 'Swallow it quickly.'),
    ('ranny', 'wounded', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rannyc.png', 'Jestem ranny.', 'I am wounded.', 'Ranny potrzebuje pomocy.', 'The wounded person needs help.'),
    ('oparzenie słoneczne', 'sunburn', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\slonce.png', 'Mam oparzenie słoneczne.', 'I have a sunburn.', 'Oparzenie słoneczne jest bolesne.', 'The sunburn is painful.'),
    ('lek przeciwbólowy', 'painkiller', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tabletka.png', 'Weź lek przeciwbólowy.', 'Take a painkiller.', 'Czy masz jakieś leki przeciwbólowe?', 'Do you have any painkillers?'),
    ('zastrzyk', 'shot', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zastrzyk.png', 'Dostałem zastrzyk.', 'I got a shot.', 'Czy zastrzyk boli?', 'Does the shot hurt?'),
	('narkotyki', 'drugs', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\narko.png', 'Unikaj narkotyków.', 'Avoid drugs.', 'Narkotyki są nielegalne.', 'Drugs are illegal.'),
    ('kroplówka', 'drip', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kroplowka.png', 'Jestem pod kroplówką.', 'I''m on a drip.', 'Kroplówka dostarcza leki.', 'The drip administers medication.'),
    ('szczepienie', 'vaccination', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\szczepienie.png', 'Muszę iść na szczepienie.', 'I need to go for a vaccination.', 'Szczepienie jest obowiązkowe.', 'The vaccination is mandatory.'),
    ('szczepionka', 'vaccine', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\szczepienie.png', 'Dostałem szczepionkę.', 'I got the vaccine.', 'Czy szczepionka jest skuteczna?', 'Is the vaccine effective?'),
    ('niepełnosprawny', 'disabled', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\niepelno.png', 'Mój brat jest niepełnosprawny.', 'My brother is disabled.', 'Niepełnosprawni mają swoje prawa.', 'The disabled have their rights.'),
    ('głuchy', 'deaf', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gluchy.png', 'Mój wujek jest głuchy.', 'My uncle is deaf.', 'Głuchy chłopiec potrzebuje tłumacza.', 'The deaf boy needs an interpreter.'),
    ('Jestem chora', 'I''m sick', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\chory.png', 'Nie mogę iść do pracy, jestem chora.', 'I can''t go to work I''m sick.', 'Jestem chora od dwóch dni.', 'I''ve been sick for two days.'),
    ('jakiś wirus', 'some kind of virus', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wirus.png', 'To chyba jakiś wirus.', 'It must be some kind of virus.', 'Lekarz powiedział, że to wirus.', 'The doctor said it''s a virus.'),
    ('układ odpornościowy', 'immune system', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\system.png', 'Muszę wzmocnić swój układ odpornościowy.', 'I need to boost my immune system.', 'Układ odpornościowy walczy z chorobą.', 'The immune system fights the illness.'),
    ('choroba śmiertelna', 'fatal illness', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\chory.png', 'To jest choroba śmiertelna.', 'This is a fatal illness.', 'Choroba śmiertelna jest trudna do zaakceptowania.', 'A fatal illness is hard to accept.'),
    ('opieka zdrowotna', 'healthcare', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\doktor.png', 'Opieka zdrowotna jest ważna.', 'Healthcare is important.', 'Musimy poprawić opiekę zdrowotną.', 'We need to improve healthcare.'),
    ('skutki uboczne', 'side effects', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wysypka.png', 'Leki mają skutki uboczne.', 'The drugs have side effects.', 'Czy są jakieś skutki uboczne?', 'Are there any side effects?'),
    ('syrop na kaszel', 'cough syrup', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\syrop.png', 'Weź syrop na kaszel.', 'Take some cough syrup.', 'Syrop na kaszel pomoże.', 'The cough syrup will help.'),
    ('poddać kwarantannie', 'quarantine', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kwarantana.png', 'Musisz się poddać kwarantannie.', 'You need to go into quarantine.', 'Poddałem się kwarantannie.', 'I went into quarantine.'),
    ('Mam grypę', 'I have the flu', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\chory.png', 'Nie mogę iść, mam grypę.', 'I can''t go I have the flu.', 'Mam grypę od tygodnia.', 'I''ve had the flu for a week.'),
    ('boli mnie głowa', 'I have a headache', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\objaw.png', 'Boli mnie głowa.', 'I have a headache.', 'Ból głowy jest nie do zniesienia.', 'The headache is unbearable.'),
	('kręci mi się w głowie', 'I feel dizzy', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zawroty.png', 'Kręci mi się w głowie.', 'I feel dizzy.', 'Zacząłem czuć zawroty głowy.', 'I started feeling dizzy.'),
    ('boli mnie ząb' , 'I have a toothache', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zab.png', 'Boli mnie ząb.', 'I have a toothache.', 'Ból zęba jest okropny.', 'The toothache is terrible.'),
    ('Boli mnie gardło', 'I have a sore throat', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gardlo.png', 'Boli mnie gardło.', 'I have a sore throat.', 'Czy masz coś na ból gardła?', 'Do you have something for a sore throat?'),
    ('Boli mnie brzuch', 'I have a stomachache', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\brzuch.png', 'Boli mnie brzuch.', 'I have a stomachache.', 'Ból brzucha mnie wykańcza.', 'The stomachache is killing me.'),
    ('Straciłem apetyt', 'I lost my appetite', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\niejesc.png', 'Straciłem apetyt.', 'I lost my appetite.', 'Nic nie jem, straciłem apetyt.', 'I don''t eat anything I lost my appetite.'),
    ('choroba lokomocyjna', 'motion sickness', 5, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wymioty.png', 'Mam chorobę lokomocyjną.', 'I have motion sickness.', 'Choroba lokomocyjna jest uciążliwa.', 'Motion sickness is bothersome.');
    
SELECT *FROM chapter_three;

INSERT INTO chapter_three(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('dezodorant', 'deodorant', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\deo.png', 'Kupiłem nowy dezodorant.', 'I bought a new deodorant.', 'Czy masz dezodorant?', 'Do you have deodorant?'),
	('golić', 'shave', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\golic.png', 'Muszę się ogolić.', 'I need to shave.', 'Czy goliłeś się dzisiaj?', 'Did you shave today?'),
	('robić pranie', 'do laundry', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\pranie.png', 'Robię pranie w sobotę.', 'I do laundry on Saturday.', 'Czy zrobiłeś już pranie?', 'Have you done the laundry yet?'),
	('szczoteczka do zębów', 'toothbrush', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\szczotka.png', 'Gdzie jest moja szczoteczka do zębów?', 'Where is my toothbrush?', 'Potrzebuję nowej szczoteczki do zębów.', 'I need a new toothbrush.'),
	('brać prysznic', 'take a shower', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\prysznic.png', 'Idę wziąć prysznic.', 'I''m going to take a shower.', 'Czy wziąłeś już prysznic?', 'Did you take a shower yet?'),
	('przewijanie', 'diaper changing', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\przewijac.png', 'Czas na przewijanie dziecka.', 'It''s time for diaper changing.', 'Czy potrzebujesz pomocy przy przewijaniu?', 'Do you need help with the diaper changing?'),
	('usunąć', 'remove', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\usunac.png', 'Musisz usunąć plamę.', 'You need to remove the stain.', 'Jak usunąć ten program?', 'How do I remove this program?'),
	('odświeżyć', 'refresh', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\odswiez.png', 'Muszę się odświeżyć.', 'I need to refresh myself.', 'Czy odświeżyłeś stronę?', 'Did you refresh the page?'),
	('rolka papieru toaletowego', 'roll of toailet paper', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\papier.png', 'Skończyła się rolka papieru toaletowego.', 'We''re out of toilet paper.', 'Gdzie jest nowa rolka papieru toaletowego?', 'Where is the new roll of toilet paper?'),
	('poranna toaleta', 'morning routine', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rano.png', 'Moja poranna toaleta trwa godzinę.', 'My morning routine takes an hour.', 'Jak wygląda twoja poranna toaleta?', 'What is your morning routine like?'),
	('nitkować zęby', 'floss', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\nic.png', 'Pamiętaj, żeby nitkować zęby.', 'Remember to floss.', 'Czy nitkujesz zęby codziennie?', 'Do you floss every day?'),
	('higiena jamy ustnej', 'ral hygiene', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\jama.png', 'Higiena jamy ustnej jest bardzo ważna.', 'Oral hygiene is very important.', 'Czy dbasz o higienę jamy ustnej?', 'Do you take care of your oral hygiene?'),
	('higiena osobista', 'personal hygiene', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\czlowiek.png', 'Higiena osobista to podstawa.', 'Personal hygiene is fundamental.', 'Jak dbasz o higienę osobistą?', 'How do you take care of your personal hygiene?'),
	('czystość', 'cleanliness', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\czysto.png', 'Czystość to podstawa.', 'Cleanliness is essential.', 'Dbam o czystość w domu.', 'I take care of cleanliness at home.'),
	('gąbka', 'sponge', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gabka.png', 'Gdzie jest gąbka do mycia naczyń?', 'Where is the sponge for washing dishes?', 'Potrzebuję nowej gąbki.', 'I need a new sponge.'),
	('myć zęby', 'clean your teeth', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\myc.png', 'Pamiętaj, żeby myć zęby dwa razy dziennie.', 'Remember to clean your teeth twice a day.', 'Czy umyłeś już zęby?', 'Did you clean your teeth yet?'),
	('dziąsło', 'gum', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\dziaslo.png', 'Mam krwawiące dziąsła.', 'My gums are bleeding.', 'Czy twoje dziąsła są zdrowe?', 'Are your gums healthy?'),
	('próchnica', 'tooth decay', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\prochnica.png', 'Mam próchnicę w jednym zębie.', 'I have tooth decay in one tooth.', 'Jak zapobiegać próchnicy?', 'How to prevent tooth decay?'),
	('dostosować', 'adjust', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\dostosowac.png', 'Muszę dostosować krzesło.', 'I need to adjust the chair.', 'Czy możesz dostosować jasność ekranu?', 'Can you adjust the screen brightness?'),
	('mydło w płynie', 'liquid soap', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\mydlo.png', 'W łazience jest mydło w płynie.', 'There is liquid soap in the bathroom.', 'Czy mamy więcej mydła w płynie?', 'Do we have more liquid soap?'),
	('nić dentystyczna', 'dental floss', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\nic.png', 'Czy masz nić dentystyczną?', 'Do you have dental floss?', 'Użyj nici dentystycznej po jedzeniu.', 'Use dental floss after eating.'),
	('płyn do płukania jamy ustnej', 'mouthwash', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\plyn.png', 'Użyj płynu do płukania jamy ustnej.', 'Use mouthwash.', 'Czy masz płyn do płukania jamy ustnej?', 'Do you have mouthwash?'),
	('mokra chusteczka', 'wet wipe', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\mokra.png', 'Weź mokrą chusteczkę.', 'Take a wet wipe.', 'Czy masz mokre chusteczki?', 'Do you have wet wipes?');
    
SELECT *FROM chapter_three;

INSERT INTO chapter_three(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('iść na odwyk', 'go to rehab', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\odwyk.png', 'Musi iść na odwyk.', 'He needs to go to rehab.', 'Postanowił iść na odwyk.', 'He decided to go to rehab.'),
	('trucizna', 'poison', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\trucizna.png', 'To jest trucizna.', 'This is poison.', 'Czy to trucizna?', 'Is this poison?'),
	('uzależniony od', 'addicted to', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\nudnosci.png', 'Jest uzależniony od narkotyków.', 'He is addicted to drugs.', 'Jest uzależniona od hazardu.', 'She is addicted to gambling.'),
	('hazard', 'gambling', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\hazard.png', 'Hazard może zniszczyć życie.', 'Gambling can ruin lives.', 'Uwielbia hazard.', 'He loves gambling.'),
	('odchylanie się od podatków', 'tax evasion', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\podatek.png', 'Odchylanie się od podatków jest nielegalne.', 'Tax evasion is illegal.', 'Został oskarżony o odchylanie się od podatków.', 'He was charged with tax evasion.'),
	('uzależnienie od narkotyków', 'drug addiction', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\drag.png', 'Uzależnienie od narkotyków jest poważnym problemem.', 'Drug addiction is a serious problem.', 'Walczą z uzależnieniem od narkotyków.', 'They are fighting drug addiction.'),
	('rzucić palenie', 'quit smoking', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rzucic.png', 'Próbuję rzucić palenie.', 'I''m trying to quit smoking.', 'Rzucił palenie pięć lat temu.', 'He quit smoking five years ago.'),
	('rozdrażniony', 'irritable', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rozd.png', 'Jest dziś bardzo rozdrażniony.', 'He is very irritable today.', 'Staje się rozdrażniona, gdy jest zmęczona.', 'She gets irritable when she''s tired.'),
	('wyjść z nałogu', 'overcome an addiction', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\odwyk.png', 'Udało mu się wyjść z nałogu.', 'He managed to overcome an addiction.', 'Pomagamy ludziom wyjść z nałogu.', 'We help people overcome addictions.'),
	('zmagać się z nałogiem', 'battle an addiction', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\plyn.png', 'Zmaga się z nałogiem od lat.', 'He has been battling an addiction for years.', 'Wielu ludzi zmaga się z nałogiem.', 'Many people battle addictions.'),
	('samorealizacja', 'self actualization', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zmagac.png', 'Dążę do samorealizacji.', 'I strive for self-actualization.', 'Samorealizacja jest ważnym celem.', 'Self-actualization is an important goal.'),
	('dym papierosowy', 'cigarette smoke', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\dym.png', 'Nie znoszę dymu papierosowego.', 'I can''t stand cigarette smoke.', 'Dym papierosowy jest szkodliwy.', 'Cigarette smoke is harmful.'),
	('wrocić do nałogu', 'relapse', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zmagac.png', 'Boję się, że wrócę do nałogu.', 'I''m afraid I will relapse.', 'Niestety, wrócił do nałogu.', 'Unfortunately, he relapsed.'),
	('środki odurzające', 'substances', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\chemia.png', 'Unikaj środków odurzających.', 'Avoid substances.', 'Środki odurzające są niebezpieczne.', 'Substances are dangerous.'),
	('narkoman', 'drug addict', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\narkot.png', 'Mój brat jest narkomanem.', 'My brother is a drug addict.', 'Pomagamy narkomanom.', 'We help drug addicts.'),
	('zaufanie', 'trust', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zaufanie.png', 'Mam do ciebie zaufanie.', 'I have trust in you.', 'Zaufanie jest ważne.', 'Trust is important.'),
	('związek/ relacja', 'relationship', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zwiazek.png', 'Mamy dobry związek.', 'We have a good relationship.', 'Relacja między nimi jest silna.', 'The relationship between them is strong.'),
	('czuć się bezpiecznie', 'feel safe', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\bezpiecznie.png', 'Czuję się bezpiecznie z tobą.', 'I feel safe with you.', 'Dzieci powinny czuć się bezpiecznie w szkole.', 'Children should feel safe at school.'),
	('brać narkotyki', 'do drugs', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\narkot.png', 'Nie bierz narkotyków.', 'Don''t do drugs.', 'On zaczął brać narkotyki.', 'He started to do drugs.'),
	('poza kontrolą', 'out of control', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kontrola.png', 'Sytuacja wymknęła się spod kontroli.', 'The situation is out of control.', 'On jest poza kontrolą.', 'He is out of control.'),
	('wdychać', 'inhale', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wdychac.png', 'Nie wdychaj tego.', 'Don''t inhale that.', 'Wdycham świeże powietrze.', 'I inhale fresh air.'),
	('zakaz palenia', 'a ban on smoking', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\ban.png', 'Wprowadzono zakaz palenia.', 'They introduced a ban on smoking.', 'Jest zakaz palenia w budynkach.', 'There is a ban on smoking in buildings.'),
	('niepalący', 'non smoker', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\ban.png', 'Jestem niepalący.', 'I''m a non-smoker.', 'Wolę przebywać z niepalącymi.', 'I prefer to be around non-smokers.'),
	('zdrowie psychiczne', 'mental health', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\psychika.png', 'Zdrowie psychiczne jest ważne.', 'Mental health is important.', 'Dba o swoje zdrowie psychiczne.', 'He takes care of his mental health.'),
	('lęk', 'anxiety', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\lek.png', 'Mam lęki.', 'I have anxiety.', 'Lęk przed wystąpieniami publicznymi jest powszechny.', 'Anxiety about public speaking is common.'),
	('podejście', 'approach', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\podejscie.png', 'Mam inne podejście.', 'I have a different approach.', 'Jego podejście do problemu było skuteczne.', 'His approach to the problem was effective.'),
	('niepewny siebie', 'insecure', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\lek.png', 'Czuję się niepewny siebie.', 'I feel insecure.', 'Był niepewny siebie w nowej pracy.', 'He was insecure in his new job.'),
	('kompleks', 'insecurity', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kompleks.png', 'Ma kompleksy.', 'He has insecurities.', 'Kompleksy mogą wpływać na życie.', 'Insecurities can affect life.'),
	('wsparcie', 'support', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wsparcie.png', 'Potrzebuję wsparcia.', 'I need support.', 'Dziękuję za wsparcie.', 'Thank you for the support.'),
	('agresywny', 'abusive', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rozd.png', 'Był agresywny wobec mnie.', 'He was abusive towards me.', 'Agresywne zachowanie nie jest akceptowalne.', 'Abusive behavior is not acceptable.'),
	('osoba uzależniona', 'addict', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zmagac.png', 'Jest osobą uzależnioną.', 'He is an addict.', 'Pomagamy osobom uzależnionym.', 'We help addicts.'),
	('alkoholik', 'alcoholic', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\alko.png', 'Jest alkoholikiem.', 'He is an alcoholic.', 'Alkoholik potrzebuje pomocy.', 'An alcoholic needs help.'),
	('nadużywanie alkoholu', 'abuse alcohol', 12, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\alko.png', 'Nadużywa alkoholu.', 'He abuses alcohol.', 'Nadużywanie alkoholu prowadzi do problemów zdrowotnych.', 'Abusing alcohol leads to health problems.');
    
INSERT INTO chapter_three(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('medytacja', 'meditation', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\medytacja.png', 'Codziennie rano uprawiam medytację.', 'I practice meditation every morning.', 'Medytacja pomaga zredukować stres.', 'Meditation helps reduce stress.'),
	('relaksować się', 'relax', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\relax.png', 'Po pracy lubię się relaksować.', 'I like to relax after work.', 'Relaksuj się w ogrodzie.', 'Relax in the garden.'),
	('mieć trochę czasu dla siebie', 'have some time to yourself', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\relax.png', 'Potrzebuję mieć trochę czasu dla siebie.', 'I need to have some time to myself.', 'Czy często masz czas dla siebie?', 'Do you often have time to yourself?'),
	('kostium kąpielowy', 'bathing suit', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kostium.png', 'Załóż kostium kąpielowy.', 'Put on your bathing suit.', 'Czy masz nowy kostium kąpielowy?', 'Do you have a new bathing suit?'),
	('zostanę w', 'I''ll stay in', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zostac.png', 'Dziś wieczorem zostanę w domu.', 'I''ll stay in tonight.', 'Zostanę w i obejrzę film.', 'I''ll stay in and watch a movie.'),
	('balsam do opalania', 'suntan lotion', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tuba.png', 'Nie zapomnij balsamu do opalania.', 'Don''t forget the suntan lotion.', 'Potrzebuję nowego balsamu do opalania.', 'I need new suntan lotion.'),
	('masaż', 'massage', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\masaz.png', 'Chciałbym umówić się na masaż.', 'I''d like to book a massage.', 'Masaż był bardzo relaksujący.', 'The massage was very relaxing.'),
	('kojący', 'calming', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tuba.png', 'Jej głos jest kojący.', 'Her voice is calming.', 'Muzyka była kojąca.', 'The music was calming.'),
	('dostępny na miejscu', 'on site', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wynajac.png', 'Basen jest dostępny na miejscu.', 'The pool is available on site.', 'Mamy restaurację dostępną na miejscu.', 'We have a restaurant on site.'),
	('uspokoić', 'reassure', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zaufanie.png', 'Próbowałem ją uspokoić.', 'I tried to reassure her.', 'Lekarz mnie uspokoił.', 'The doctor reassured me.'),
	('napięcie', 'tension', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\objaw.png','Czuję napięcie w mięśniach.', 'I feel tension in my muscles.', 'Napięcie w zespole rosło.', 'Tension in the team was growing.'),
	('opalać się', 'sunbathe', 14, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\opalac.png', 'Lubię opalać się na plaży.', 'I like to sunbathe on the beach.', 'Czy chcesz się opalać?', 'Do you want to sunbathe?'),
	('czuć się jak nowo narodzony', 'feel like you''re born again', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\baby.png', 'Po wakacjach czuję się jak nowo narodzony.', 'I feel like I''m born again after the vacation.', 'Po długim śnie czuję się jak nowo narodzony.', 'I feel like I''m born again after a long sleep.'),
	('zasnąć', 'fall asleep', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\senny.png', 'Nie mogłem zasnąć wczoraj wieczorem.', 'I couldn''t fall asleep last night.', 'Zasnąłem szybko po pracy.', 'I fell asleep quickly after work.'),
	('zdrzemnąć się', 'take a nap', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\senny.png', 'Zdrzemnij się, jeśli jesteś zmęczony.', 'Take a nap if you''re tired.', 'Lubię się zdrzemnąć po obiedzie.', 'I like to take a nap after lunch.'),
	('przyjemności dla ciała', 'the pleasures of the flesh', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\masaz.png', 'Spa oferuje przyjemności dla ciała.', 'The spa offers the pleasures of the flesh.', 'Cieszył się przyjemnościami dla ciała.', 'He enjoyed the pleasures of the flesh.'),
	('grać na instrumencie', 'play an instrument', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gitara.png', 'Uczy się grać na instrumencie.', 'She is learning to play an instrument.', 'Czy potrafisz grać na instrumencie?', 'Can you play an instrument?'),
	('codzienne zajęcia', 'daily routine', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\pranie.png', 'Moje codzienne zajęcia obejmują jogę.', 'My daily routine includes yoga.', 'Jakie są twoje codzienne zajęcia?', 'What is your daily routine?'),
	('rozrywka', 'pastime', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\salon.png', 'Czytanie książek to moja ulubiona rozrywka.', 'Reading books is my favorite pastime.', 'Jakie są twoje ulubione rozrywki?', 'What are your favorite pastimes?'),
	('długi weekend', 'long weekend', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\weekend.png', 'Planujemy długi weekend nad morzem.', 'We''re planning a long weekend at the sea.', 'Długi weekend to świetna okazja do odpoczynku.', 'A long weekend is a great opportunity to relax.'),
	('gra planszowa', 'board game', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gra.png', 'Lubię grać w gry planszowe.', 'I like to play board games.', 'Czy masz jakąś ulubioną grę planszową?', 'Do you have a favorite board game?'),
	('czas wolny', 'free time', 15, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\salon.png', 'Co robisz w czasie wolnym?', 'What do you do in your free time?', 'Mam dużo wolnego czasu w weekendy.', 'I have a lot of free time on weekends.');
    
INSERT INTO chapter_three(polski,angielski,poziom,obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('wzmacniać charakter', 'build character', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\charakter.png', 'Sport wzmacnia charakter.', 'Sports build character.', 'Trudne sytuacje wzmacniają charakter.', 'Difficult situations build character.'),
	('usunąć mnie z drużyny', 'take me off the team', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\druzyna.png', 'Trener usunął mnie z drużyny.', 'The coach took me off the team.', 'Dlaczego usunięto mnie z drużyny?', 'Why was I taken off the team?'),
	('ostateczna rozrywka', 'showdown', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rozgrywka.png', 'Dziś wieczorem będzie ostateczna rozrywka.', 'Tonight will be the showdown.', 'Czekam na ostateczną rozrywkę.', 'I am waiting for the showdown.'),
	('dostałem się do drużyny', 'I made the team', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\team.png', 'Dostałem się do drużyny!', 'I made the team!', 'Cieszę się, że dostałem się do drużyny.', 'I am happy I made the team.'),
	('wydarzenie sportowe', 'sports event', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\sport.png', 'Jutro odbędzie się wydarzenie sportowe.', 'There will be a sports event tomorrow.', 'Uczestniczę w wydarzeniu sportowym.', 'I am participating in a sports event.'),
	('relacjonować', 'relay', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\relacja.png', 'Będziemy relacjonować mecz na żywo.', 'We will relay the match live.', 'Relacjonuję wydarzenia sportowe.', 'I relay sports events.'),
	('kibic', 'fan', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\fan.png', 'Jestem kibicem tej drużyny.', 'I am a fan of this team.', 'Kibicuję mojemu synowi.', 'I am a fan of my son.'),
	('wynik', 'score', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\wynik.png', 'Jaki jest wynik meczu?', 'What is the score of the match?', 'Sprawdźmy wynik.', 'Let''s check the score.'),
	('występ', 'performance', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\przedstawienie.png', 'Jego występ był niesamowity.', 'His performance was amazing.', 'Oceniam twój występ na 10.', 'I rate your performance a 10.'),
	('podanie', 'pass', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\podac.png', 'Świetne podanie!', 'Great pass!', 'Przećwiczmy podania.', 'Let''s practice passes.'),
	('sportowy', 'athletic', 17, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\sportowy.png', 'Mam sportowy styl życia.', 'I have an athletic lifestyle.', 'Moje dziecko jest bardzo sportowe.', 'My child is very athletic.'),
	('kolega z drużyny', 'teammate', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\team.png', 'Mój kolega z drużyny jest świetny.', 'My teammate is great.', 'Znamy się od lat jako koledzy z drużyny.', 'We''ve known each other for years as teammates.'),
	('turniej', 'tournament', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\rozgrywka.png', 'Wzięliśmy udział w turnieju.', 'We participated in a tournament.', 'Kiedy zaczyna się turniej?', 'When does the tournament start?'),
	('pokonać', 'beat', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\pokonac.png', 'Pokonaliśmy przeciwników.', 'We beat the opponents.', 'Czy mogę cię pokonać?', 'Can I beat you?'),
	('mecz', 'match', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\match.png', 'Idziemy na mecz piłki nożnej.', 'We are going to a soccer match.', 'O której jest mecz?', 'What time is the match?'),
	('dzika karta', 'wild card', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\dzika.png', 'Otrzymaliśmy dziką kartę.', 'We received a wild card.', 'Czy to jest dzika karta?', 'Is this a wild card?'),
	('awansować do', 'advance to', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\awansowac.png', 'Awansowaliśmy do finału.', 'We advanced to the finals.', 'Czy możemy awansować do następnej rundy?', 'Can we advance to the next round?'),
	('runda', 'round', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\runda.png', 'To była pierwsza runda.', 'That was the first round.', 'Jestem gotowy na kolejną rundę.', 'I am ready for the next round.'),
	('tor', 'lane', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tor.png', 'Biegnij w swoim torze.', 'Run in your lane.', 'To jest mój tor.', 'This is my lane.'),
	('czas', 'timeout', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\czas.png', 'Bierzemy czas.', 'We are taking a timeout.', 'Potrzebuję czasu.', 'I need a timeout.'),
	('trener', 'coach', 18, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\trener.png', 'Mój trener jest świetny.', 'My coach is great.', 'Słucham mojego trenera.', 'I listen to my coach.'),
	('obrona', 'defense', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\obrona.png', 'Nasza obrona jest silna.', 'Our defense is strong.', 'Pracujemy nad obroną.', 'We are working on defense.'),
	('uprawiać sport', 'do sports', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\uprawiac.png', 'Lubię uprawiać sport.', 'I like to do sports.', 'Jakie sporty uprawiasz?', 'What sports do you do?'),
	('aktywność fizyczna', 'physical activity', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\aktywnosc.png', 'Codziennie mam aktywność fizyczną.', 'I have physical activity every day.', 'Jakie są twoje ulubione aktywności fizyczne?', 'What are your favorite physical activities?'),
	('gimnastyka', 'exercise', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\gimnastyka.png', 'Gimnastyka jest ważna.', 'Exercise is important.', 'Zrobiłem gimnastykę rano.', 'I did exercise in the morning.'),
	('tryb', 'mode', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\mode.png', 'Jestem w trybie sportowym.', 'I am in sports mode.', 'Zmień tryb na relaksacyjny.', 'Switch to relaxation mode.'),
	('spalać kalorie', 'burn calories', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\kalorie.png', 'Bieganie spala kalorie.', 'Running burns calories.', 'Chcę spalać więcej kalorii.', 'I want to burn more calories.'),
	('intensywny', 'intensive', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\intensywnie.png', 'Mamy intensywny trening.', 'We have an intensive workout.', 'To był intensywny dzień.', 'That was an intensive day.'),
	('mięsień', 'muscle', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\miesien.png', 'Boli mnie mięsień.', 'My muscle hurts.', 'Zbudowałem mięśnie.', 'I built muscles.'),
	('sprawny fizycznie', 'fit', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\fit.png', 'Jestem sprawny fizycznie.', 'I am fit.', 'Jak być bardziej sprawnym fizycznie?', 'How to be more fit?'),
	('boisko', 'court', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\boisko.png', 'Spotkajmy się na boisku.', 'Let''s meet on the court.', 'Gramy na nowym boisku.', 'We are playing on a new court.'),
	('stanie na rękach', 'handstand', 19, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\fit.png', 'Ćwiczę stanie na rękach.', 'I am practicing handstands.', 'Zrobiłem stanie na rękach.', 'I did a handstand.'),
	('puchar', 'cup', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\sport.png', 'Zdobyliśmy puchar!', 'We won the cup!', 'Puchar wygląda świetnie.', 'The cup looks great.'),
	('szalik', 'scarf', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\szalik.png', 'Noszę szalik drużyny.', 'I wear a team scarf.', 'Czy masz nowy szalik?', 'Do you have a new scarf?'),
	('sport drużynowy', 'team sport', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\team.png', 'Lubię sport drużynowy.', 'I like team sports.', 'Jakie sport drużynowy preferujesz?', 'What team sport do you prefer?'),
	('zawodnik', 'player', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\sportowy.png', 'Jestem zawodnikiem tej drużyny.', 'I am a player on this team.', 'Zawodnicy są gotowi.', 'The players are ready.'),
	('duch drużyny', 'team spirit', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\duch.png', 'Mamy silny duch drużyny.', 'We have strong team spirit.', 'Duch drużyny jest ważny.', 'Team spirit is important.'),
	('wydarzenie sportowe', 'sporting event', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\relacja.png', 'Idziemy na wydarzenie sportowe.', 'We are going to a sporting event.', 'To jest duże wydarzenie sportowe.', 'This is a big sporting event.'),
	('biec maraton', 'run a marathon', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\biec.png', 'Biegłem maraton.', 'I ran a marathon.', 'Czy kiedykolwiek biegłeś maraton?', 'Have you ever run a marathon?'),
	('tor wyścigowy', 'motor racing circuit', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\tor2.png', 'To jest nowy tor wyścigowy.', 'This is a new motor racing circuit.', 'Lubię oglądać wyścigi na torze wyścigowym.', 'I like to watch races on the motor racing circuit.'),
	('iść na siłownie', 'hit the gym', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\silownia.png', 'Muszę iść na siłownię.', 'I need to hit the gym.', 'Chcesz iść na siłownię?', 'Do you want to hit the gym?'),
	('wysiłek fizyczny', 'physical strain', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\intensywnie.png', 'To był duży wysiłek fizyczny.', 'That was a lot of physical strain.', 'Uważaj na wysiłek fizyczny.', 'Watch out for physical strain.'),
	('sportowiec', 'athlete', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\match.png', 'On jest sportowcem.', 'He is an athlete.', 'Znam wielu sportowców.', 'I know many athletes.'),
	('zakwasy', 'muscle fever', 20, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons3\\zakwas.png', 'Mam zakwasy po treningu.', 'I have muscle fever after the workout.', 'Jak złagodzić zakwasy?', 'How to relieve muscle fever?');
    
    DROP TABLE chapter_three;