USE chapter_seven;

CREATE TABLE chapter_seven
(
	polski VARCHAR(300),
    angielski VARCHAR(300),
    poziom INT,
    obraz VARCHAR(400),
	przyklada VARCHAR(400),
    przykladb VARCHAR(400),
    przykladc VARCHAR(400),
    przykladd VARCHAR(400)
);

INSERT INTO chapter_seven(polski, angielski, poziom, obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('zrobić rezerwację', 'make a reservation', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\reser.png', 'Chciałbym zrobić rezerwację na jutro.', 'I would like to make a reservation for tomorrow.', 'Czy mogę zrobić rezerwację?', 'Can I make a reservation?'),
    ('stolik dla 2 osób', 'a table for two', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\stol.png', 'Poproszę stolik dla 2 osób.', 'A table for two, please.', 'Czy mają Państwo stolik dla 2 osób?', 'Do you have a table for two?'),
    ('serwować', 'serve', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\serve.png', 'Czy mogę Panią/Pana obsłużyć?', 'May I serve you?', 'Czy serwujecie śniadania?', 'Do you serve breakfast?'),
    ('zjeść poza domem', 'eat out', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\poza.png', 'Lubię zjeść poza domem w weekendy.', 'I like to eat out on weekends.', 'Czy często zjadasz poza domem?', 'Do you often eat out?'),
    ('mikrofalówka', 'microwave', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\mikro.png', 'Podgrzewam obiad w mikrofalówce.', 'I am heating my lunch in the microwave.', 'Czy masz mikrofalówkę w domu?', 'Do you have a microwave at home?'),
    ('kolacja', 'dinner', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\kolacja.png', 'Kolacja będzie gotowa o 19:00.', 'Dinner will be ready at 7 PM.', 'O której godzinie jest kolacja?', 'What time is dinner?'),
    ('śniadanie', 'breakfast', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\sniad.png', 'Śniadanie jest najważniejszym posiłkiem dnia.', 'Breakfast is the most important meal of the day.', 'Co zwykle jesz na śniadanie?', 'What do you usually eat for breakfast?'),
    ('obiad', 'lunch', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\obiad.png', 'Mam spotkanie biznesowe podczas obiadu.', 'I have a business meeting during lunch.', 'Czy zjesz ze mną obiad?', 'Will you have lunch with me?'),
    ('surowy', 'raw', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\raw.png', 'Czy to mięso jest surowe?', 'Is this meat raw?', 'Lubię jeść surowe warzywa.', 'I like to eat raw vegetables.'),
    ('przysmak', 'delicacy', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\przys.png', 'To danie to prawdziwy przysmak.', 'This dish is a real delicacy.', 'Czy próbowałeś kiedyś tego przysmaku?', 'Have you ever tried this delicacy?'),
    ('zamówienie', 'order', 1, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\order.png', 'Złożyłem zamówienie online.', 'I placed an order online.', 'Czy moje zamówienie jest gotowe?', 'Is my order ready?'),
    ('Czy mogę przyjąć zamówienie', 'May I take your order?', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\order.png', 'Czy mogę przyjąć zamówienie?', 'May I take your order?', 'Czy możemy teraz złożyć zamówienie?', 'Can we place our order now?'),
    ('bezkofeinowa', 'decaf', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\bez.png', 'Poproszę kawę bezkofeinową.', 'I''ll have a decaf coffee.', 'Czy masz bezkofeinową herbatę?', 'Do you have decaf tea?'),
    ('ugryźć', 'take a bite', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\gryz.png', 'Chciałbym spróbować tego ciasta. Mogę ugryźć?', 'I’d like to try this cake. Can I take a bite?', 'Czy mogę ugryźć kawałek twojego jabłka?', 'Can I take a bite of your apple?'),
    ('Z czym jest podawany?', 'What comes with that?', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\czym.png', 'Z czym jest podawany ten stek?', 'What comes with that steak?', 'Z czym podawane są frytki?', 'What comes with the fries?'),
    ('zastąpić', 'substitute', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\zastap.png', 'Czy mogę zastąpić frytki sałatką?', 'Can I substitute fries with a salad?', 'Czy mogę zastąpić kawę herbatą?', 'Can I substitute coffee with tea?'),
    ('Proszę to samo', 'I''ll have the same', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\samo.png', 'Proszę to samo dla mnie.', 'I’ll have the same.', 'Poproszę to samo, co on.', 'I’ll have the same as him.'),
    ('posiłek', 'meal', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\meal.png', 'Ten posiłek jest bardzo smaczny.', 'This meal is very tasty.', 'Czy smakował Ci posiłek?', 'Did you enjoy the meal?'),
    ('upiec', 'roast', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\roast.png', 'Zamierzam upiec kurczaka na kolację.', 'I’m going to roast a chicken for dinner.', 'Czy możesz upiec ziemniaki?', 'Can you roast the potatoes?'),
    ('rachunek', 'bill', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\bill.png', 'Proszę przynieść rachunek.', 'Please bring the bill.', 'Czy możemy prosić o rachunek?', 'Can we have the bill, please?'),
    ('na wynos', 'to go', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\go.png', 'Czy to jest na wynos?', 'Is this to go?', 'Poproszę kawę na wynos.', 'I’d like a coffee to go.'),
    ('wegetarianizm', 'vegeterian', 2, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\vegeterian.png', 'Praktykuję wegetarianizm od 5 lat.', 'I’ve been a vegetarian for 5 years.', 'Czy jesteś wegetarianinem?', 'Are you a vegetarian?'),
    ('słomka', 'straw', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\straw.png', 'Czy możesz podać mi słomkę?', 'Can you give me a straw?', 'Czy mają Państwo słomki?', 'Do you have straws?'),
    ('napiwek', 'tip', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\tip.png', 'Czy mogę zostawić napiwek?', 'Can I leave a tip?', 'Jak duży powinien być napiwek?', 'How much should the tip be?'),
    ('zamówić jedzenie z dowozem', 'order in', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\dowoz.png', 'Zamówię jedzenie z dowozem na kolację.', 'I will order in for dinner.', 'Czy możemy zamówić jedzenie z dowozem?', 'Can we order in?'),
    ('danie wegańskie', 'vegan meal', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\vegetarian.png', 'Poproszę danie wegańskie.', 'I’d like a vegan meal.', 'Czy mają Państwo dania wegańskie?', 'Do you have vegan meals?'),
    ('bezglutenowy', 'gluten-free', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\glut.png', 'Czy masz coś bezglutenowego?', 'Do you have anything gluten-free?', 'Czy ten chleb jest bezglutenowy?', 'Is this bread gluten-free?'),
    ('Proszę dołączyć do mojego rachunku', 'Put it on my tab', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\bill.png', 'Proszę dołączyć to do mojego rachunku.', 'Put it on my tab.', 'Czy możesz to dołączyć do mojego rachunku?', 'Can you put it on my tab?'),
    ('Ja stawiam', 'It''s my treat', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\tip.png', 'Ja stawiam kolację.', 'It’s my treat for dinner.', 'Dziś ja stawiam.', 'Today, it’s my treat.'),
    ('przystawka', 'appetizer', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\appetizer.png', 'Na przystawkę zamówiłem sałatkę.', 'I ordered a salad as an appetizer.', 'Jaką przystawkę polecasz?', 'What appetizer do you recommend?'),
    ('danie główne', 'main course', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\glowne.png', 'Na danie główne zamówiłem stek.', 'I ordered a steak for the main course.', 'Co polecasz na danie główne?', 'What do you recommend for the main course?'),
    ('słodycze', 'candy', 3, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\candy.png', 'Czy lubisz słodycze?', 'Do you like candy?', 'Mam ochotę na coś słodkiego.', 'I’m craving some candy.'),
    ('białko', 'protein', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\protein.png', 'To danie jest bogate w białko.', 'This dish is rich in protein.', 'Jakie produkty są bogate w białko?', 'Which foods are rich in protein?'),
    ('pikantny', 'spicy', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\spicy.png', 'Lubię pikantne jedzenie.', 'I like spicy food.', 'Czy to danie jest pikantne?', 'Is this dish spicy?'),
    ('ostry', 'hot', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\spicy.png', 'To danie jest bardzo ostre.', 'This dish is very hot.', 'Czy mogę prosić o mniej ostre danie?', 'Can I have a less hot dish?'),
    ('karta', 'menu', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\menu.png', 'Czy mogę zobaczyć kartę?', 'Can I see the menu?', 'Czy masz kartę dań?', 'Do you have a menu?'),
    ('przepis', 'recipe', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\recipe.png', 'Masz dobry przepis na ciasto?', 'Do you have a good recipe for cake?', 'Czy możesz podać mi przepis?', 'Can you give me the recipe?'),
    ('zamrożony', 'frozen', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\frozen.png', 'Mam zamrożoną pizzę na kolację.', 'I have a frozen pizza for dinner.', 'Czy to jest zamrożone mięso?', 'Is this meat frozen?'),
    ('przyprawa', 'spice', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\spice.png', 'Dodaj trochę przyprawy do zupy.', 'Add some spice to the soup.', 'Jakiej przyprawy użyłeś?', 'What spice did you use?'),
    ('ilość', 'quantity', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\quantity.png', 'Jaką ilość cukru dodałeś?', 'What quantity of sugar did you add?', 'Czy możesz zmniejszyć ilość soli?', 'Can you reduce the quantity of salt?'),
    ('sos', 'sauce', 4, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\sauce.png', 'Czy ten sos jest ostry?', 'Is this sauce hot?', 'Jaki rodzaj sosu preferujesz?', 'What kind of sauce do you prefer?');
    
INSERT INTO chapter_seven(polski, angielski, poziom, obraz, przyklada, przykladb, przykladc, przykladd)
VALUES
	('owoce', 'fruits', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\fruits.png', 'Czy lubisz owoce?', 'Do you like fruits?', 'Moje ulubione owoce to truskawki.', 'My favorite fruits are strawberries.'),
    ('jabłko', 'apple', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\apple.png', 'Zjadłem jabłko na drugie śniadanie.', 'I had an apple for my mid-morning snack.', 'Czy masz ochotę na jabłko?', 'Do you want an apple?'),
    ('banan', 'banana', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\banana.png', 'Banany są pełne potasu.', 'Bananas are full of potassium.', 'Kupiłem dojrzałego banana.', 'I bought a ripe banana.'),
    ('pomarańcz', 'orange', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\orange.png', 'Pomarańcze są bogate w witaminę C.', 'Oranges are rich in vitamin C.', 'Czy mogę dostać sok z pomarańczy?', 'Can I have orange juice?'),
    ('truskawka', 'strawberry', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\strawberry.png', 'Czy możesz podać mi truskawkę?', 'Can you pass me a strawberry?', 'Uwielbiam smak świeżych truskawek.', 'I love the taste of fresh strawberries.'),
    ('winogrono', 'grape', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\grape.png', 'Winogrona są bardzo słodkie.', 'Grapes are very sweet.', 'Chcesz trochę winogron?', 'Do you want some grapes?'),
    ('arbuz', 'watermelon', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\watermelon.png', 'Arbuzy są świetne na upalne dni.', 'Watermelons are great for hot days.', 'Czy lubisz jeść arbuzy?', 'Do you like eating watermelons?'),
    ('ananas', 'pineapple', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pineapple.png', 'Ananas ma wyjątkowy smak.', 'Pineapple has a unique flavor.', 'Czy próbowałeś świeżego ananasa?', 'Have you tried fresh pineapple?'),
    ('mango', 'mango', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\mango.png', 'Mango to mój ulubiony owoc.', 'Mango is my favorite fruit.', 'Czy jadłeś kiedyś mango?', 'Have you ever eaten a mango?'),
    ('kiwi', 'kiwi', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\kiwi.png', 'Kiwi jest pełne witaminy C.', 'Kiwi is full of vitamin C.', 'Czy mogę dostać kawałek kiwi?', 'Can I have a slice of kiwi?'),
    ('wiśnia', 'cherry', 6, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cherry.png', 'Chciałbym spróbować wiśni.', 'I’d like to try a cherry.', 'Wiśnie są kwaśne, ale smaczne.', 'Cherries are sour but tasty.'),
    ('warzywa', 'vegetables', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\vegetables.png', 'Czy jesz dużo warzyw?', 'Do you eat a lot of vegetables?', 'Warzywa są zdrowe i odżywcze.', 'Vegetables are healthy and nutritious.'),
    ('marchewka', 'carrot', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\carrot.png', 'Marchewki są dobre dla wzroku.', 'Carrots are good for your eyesight.', 'Czy masz trochę marchewki?', 'Do you have some carrots?'),
    ('pomidor', 'tomato', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\tomato.png', 'Pomidor jest technicznie owocem.', 'A tomato is technically a fruit.', 'Czy chcesz dodać pomidory do sałatki?', 'Do you want to add tomatoes to the salad?'),
    ('ziemniak', 'potato', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\potato.png', 'Ziemniaki są podstawą wielu dań.', 'Potatoes are a staple in many dishes.', 'Czy lubisz pieczone ziemniaki?', 'Do you like baked potatoes?'),
    ('cebula', 'onion', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\onion.png', 'Cebula dodaje smaku potrawom.', 'Onions add flavor to dishes.', 'Czy możesz posiekać cebulę?', 'Can you chop the onion?'),
    ('sałata', 'lettuce', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\lettuce.png', 'Sałata jest podstawą każdej sałatki.', 'Lettuce is the base of any salad.', 'Czy masz trochę sałaty?', 'Do you have some lettuce?'),
    ('szpinak', 'spinach', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\spinach.png', 'Szpinak jest bogaty w żelazo.', 'Spinach is rich in iron.', 'Czy lubisz szpinak?', 'Do you like spinach?'),
    ('brokuł', 'broccoli', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\broccoli.png', 'Brokuły są bardzo zdrowe.', 'Broccoli is very healthy.', 'Czy chcesz trochę brokułów?', 'Do you want some broccoli?'),
    ('ogórek', 'cucumber', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cucumber.png', 'Ogórek jest bardzo orzeźwiający.', 'Cucumber is very refreshing.', 'Czy mogę dostać ogórka do sałatki?', 'Can I have a cucumber for the salad?'),
    ('groszek', 'pea', 7, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pea.png', 'Groszek jest słodki i delikatny.', 'Peas are sweet and tender.', 'Czy lubisz groszek w zupie?', 'Do you like peas in soup?'),
    ('kukurydza', 'corn', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\corn.png', 'Kukurydza jest często używana w kuchni.', 'Corn is often used in cooking.', 'Czy masz trochę kukurydzy?', 'Do you have some corn?'),
    ('papryka', 'pepper', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pepper.png', 'Papryka dodaje koloru i smaku.', 'Pepper adds color and flavor.', 'Czy chcesz trochę papryki?', 'Do you want some pepper?'),
    ('mięso', 'meat', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\meat.png', 'Czy lubisz mięso?', 'Do you like meat?', 'Jakie mięso preferujesz?', 'What kind of meat do you prefer?'),
    ('wołowina', 'beef', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\beef.png', 'Wołowina jest bogata w białko.', 'Beef is rich in protein.', 'Czy chcesz zjeść wołowinę na obiad?', 'Do you want to eat beef for dinner?'),
    ('kurczak', 'chicken', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\chicken.png', 'Kurczak jest zdrową opcją.', 'Chicken is a healthy option.', 'Czy mogę dostać smażonego kurczaka?', 'Can I have fried chicken?'),
    ('wieprzowina', 'pork', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pork.png', 'Wieprzowina ma dużo smaku.', 'Pork has a lot of flavor.', 'Czy lubisz wieprzowinę?', 'Do you like pork?'),
    ('jagnięcina', 'lamb', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\lamb.png', 'Jagnięcina jest delikatna i smaczna.', 'Lamb is tender and tasty.', 'Czy próbowałeś jagnięciny?', 'Have you tried lamb?'),
    ('indyk', 'turkey', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\turkey.png', 'Indyk jest popularny na Święto Dziękczynienia.', 'Turkey is popular on Thanksgiving.', 'Czy jadasz indyka?', 'Do you eat turkey?'),
    ('kaczka', 'duck', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\duck.png', 'Kaczka ma wyjątkowy smak.', 'Duck has a unique flavor.', 'Czy lubisz kaczki?', 'Do you like duck?'),
    ('ryba', 'fish', 8, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\fish.png', 'Ryba jest zdrowa i lekka.', 'Fish is healthy and light.', 'Czy często jesz ryby?', 'Do you eat fish often?'),
    ('łosoś', 'salmon', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\salmon.png', 'Łosoś jest bogaty w omega-3.', 'Salmon is rich in omega-3.', 'Czy lubisz wędzonego łososia?', 'Do you like smoked salmon?'),
    ('krewetka', 'shrimp', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\shrimp.png', 'Krewetki są delikatne i smaczne.', 'Shrimp is tender and tasty.', 'Czy lubisz krewetki?', 'Do you like shrimp?'),
    ('nabiał', 'dairy', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\dairy.png', 'Czy lubisz nabiał?', 'Do you like dairy?', 'Jakie produkty nabiałowe preferujesz?', 'What dairy products do you prefer?'),
    ('mleko', 'milk', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\dairy.png', 'Mleko jest bogate w wapń.', 'Milk is rich in calcium.', 'Czy pijesz mleko?', 'Do you drink milk?'),
    ('ser', 'cheese', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cheese.png', 'Ser jest dobrym dodatkiem do wielu potraw.', 'Cheese is a good addition to many dishes.', 'Czy lubisz żółty ser?', 'Do you like yellow cheese?'),
    ('jogurt', 'yogurt', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\yogurt.png', 'Jogurt jest zdrową przekąską.', 'Yogurt is a healthy snack.', 'Czy jesz jogurt na śniadanie?', 'Do you eat yogurt for breakfast?'),
    ('masło', 'butter', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\butter.png', 'Masło jest używane do gotowania.', 'Butter is used for cooking.', 'Czy masz trochę masła?', 'Do you have some butter?'),
    ('śmietana', 'cream', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cream.png', 'Śmietana jest dodawana do zup.', 'Cream is added to soups.', 'Czy możesz dodać śmietanę do sosu?', 'Can you add cream to the sauce?'),
    ('twaróg', 'cottage cheese', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cottage.png', 'Twaróg jest lekki i zdrowy.', 'Cottage cheese is light and healthy.', 'Czy lubisz jeść twaróg?', 'Do you like eating cottage cheese?'),
    ('jajka', 'eggs', 9, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\eggs.png', 'Jajka są wszechstronnym składnikiem.', 'Eggs are a versatile ingredient.', 'Czy możesz ugotować jajka?', 'Can you cook the eggs?'),
    ('zboża', 'grains', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\grains.png', 'Czy jesz zboża na śniadanie?', 'Do you eat grains for breakfast?', 'Jakie zboża preferujesz?', 'What grains do you prefer?'),
    ('chleb', 'bread', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\bread.png', 'Chleb jest podstawą wielu diet.', 'Bread is a staple in many diets.', 'Czy masz świeży chleb?', 'Do you have fresh bread?'),
    ('ryż', 'rice', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\rice.png', 'Ryż jest popularny w wielu kulturach.', 'Rice is popular in many cultures.', 'Czy lubisz biały czy brązowy ryż?', 'Do you like white or brown rice?'),
    ('makaron', 'pasta', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pasta.png', 'Makaron jest uniwersalnym składnikiem.', 'Pasta is a versatile ingredient.', 'Czy lubisz włoski makaron?', 'Do you like Italian pasta?'),
    ('owies', 'oats', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\oats.png', 'Owies jest zdrowym wyborem na śniadanie.', 'Oats are a healthy choice for breakfast.', 'Czy jadasz owsiankę?', 'Do you eat oatmeal?'),
    ('jęczmień', 'barley', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\barley.png', 'Jęczmień jest dobry na zupę.', 'Barley is good for soup.', 'Czy próbowałeś zupy z jęczmienia?', 'Have you tried barley soup?'),
    ('napoje', 'beverages', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\beverages.png', 'Czy pijesz dużo napojów?', 'Do you drink a lot of beverages?', 'Jakie napoje preferujesz?', 'What beverages do you prefer?'),
    ('woda', 'water', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\water.png', 'Woda jest niezbędna do życia.', 'Water is essential for life.', 'Czy pijesz wystarczająco dużo wody?', 'Do you drink enough water?'),
    ('herbata', 'tea', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\tea.png', 'Herbata jest popularnym napojem na całym świecie.', 'Tea is a popular drink worldwide.', 'Czy lubisz herbatę z mlekiem?', 'Do you like tea with milk?'),
    ('kawa', 'coffe', 10, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\coffe.png', 'Kawa jest powszechnie pijana rano.', 'Coffee is commonly drunk in the morning.', 'Czy pijesz kawę każdego dnia?', 'Do you drink coffee every day?'),
    ('sok', 'juice', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\juice.png', 'Sok jest zdrową alternatywą dla napojów gazowanych.', 'Juice is a healthy alternative to soda.', 'Czy pijesz świeży sok?', 'Do you drink fresh juice?'),
    ('wino', 'wine', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\wine.png', 'Wino jest popularne na przyjęciach.', 'Wine is popular at parties.', 'Czy pijesz czerwone czy białe wino?', 'Do you drink red or white wine?'),
    ('piwo', 'beer', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\beer.png', 'Piwo jest często pijane na imprezach.', 'Beer is often drunk at parties.', 'Czy lubisz piwo?', 'Do you like beer?'),
    ('koktajle', 'cocktails', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cocktails.png', 'Koktajle są pyszne i orzeźwiające.', 'Cocktails are delicious and refreshing.', 'Czy lubisz pić koktajle?', 'Do you like drinking cocktails?'),
    ('desery', 'desserts', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\desserts.png', 'Czy lubisz desery?', 'Do you like desserts?', 'Jakie desery preferujesz?', 'What desserts do you prefer?'),
    ('ciasto', 'cake', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cake.png', 'Ciasto jest moim ulubionym deserem.', 'Cake is my favorite dessert.', 'Czy upieczesz ciasto na urodziny?', 'Will you bake a cake for the birthday?'),
    ('lody', 'ice cream', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\ice.png', 'Lody są idealne na upalne dni.', 'Ice cream is perfect for hot days.', 'Czy masz ochotę na lody?', 'Do you want some ice cream?'),
    ('ciasteczka', 'cookies', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cookies.png', 'Ciasteczka są świetną przekąską.', 'Cookies are a great snack.', 'Czy masz przepis na ciasteczka?', 'Do you have a recipe for cookies?'),
    ('budyń', 'pudding', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\pudding.png', 'Budynie są gładkie i kremowe.', 'Puddings are smooth and creamy.', 'Czy próbowałeś czekoladowego budyniu?', 'Have you tried chocolate pudding?'),
    ('pączek', 'donut', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\donut.png', 'Pączki są popularne na śniadanie.', 'Donuts are popular for breakfast.', 'Czy lubisz pączki?', 'Do you like donuts?'),
    ('babeczka', 'cupcake', 11, 'C:\\Users\\trapi\\Desktop\\Kurs\\Icons7\\cupcake.png', 'Babeczki są małe i słodkie.', 'Cupcakes are small and sweet.', 'Czy upieczesz babeczki na imprezę?', 'Will you bake cupcakes for the party?');
    
SELECT *FROM chapter_seven;

DROP TABLE chapter_seven;
    